"use client";

import { useMemo, useState } from "react";
import type { TimetableAnalysis } from "../../../lib/timetable-analyser";
import { autoScheduleDuties, countStaffTeachingPeriodByDay, DUTY_SCHOOL_DAYS, DUTY_TIME_OPTIONS, expandDutyDefinitions, getDutySchedulerStaff, summariseManualSchedule, type DutyAssignmentSlot, type DutyDefinitionRow, type DutyTime } from "../../../lib/duty-scheduler";

type SavedTimetableImport = { id: number; name: string; sourceFilename: string; isActive: boolean; createdAt: string; updatedAt: string; analysis: TimetableAnalysis };

function newDuty(index: number): DutyDefinitionRow { return { id: `duty-${Date.now()}-${index}`, description: "", time: "Breaktime" }; }
function staffDisplay(staff: { staffName: string; staffCode: string }) { return `${staff.staffName} (${staff.staffCode})`; }
function names(rows: { staffName: string; staffCode: string }[]) { return rows.length ? rows.map(staffDisplay).join(", ") : "None"; }
function dayCountsText(counts: Record<string, number>) { return DUTY_SCHOOL_DAYS.map(day => `${day.slice(0, 3)} ${counts[day]}`).join(" · "); }

export function DutySchedulerForm({ timetable }: { timetable: SavedTimetableImport }) {
  const staff = useMemo(() => getDutySchedulerStaff(timetable.analysis), [timetable.analysis]);
  const p2Counts = useMemo(() => countStaffTeachingPeriodByDay(staff, "P2"), [staff]);
  const p5Counts = useMemo(() => countStaffTeachingPeriodByDay(staff, "P5"), [staff]);
  const [definitions, setDefinitions] = useState<DutyDefinitionRow[]>([newDuty(1)]);
  const [assignments, setAssignments] = useState<DutyAssignmentSlot[]>([]);
  const [scheduleMessage, setScheduleMessage] = useState<string | null>(null);
  const expandedAssignments = useMemo(() => expandDutyDefinitions(definitions, assignments), [definitions, assignments]);
  const summary = useMemo(() => summariseManualSchedule(expandedAssignments, staff), [expandedAssignments, staff]);

  function addDuty() { setDefinitions(current => [...current, newDuty(current.length + 1)]); setScheduleMessage(null); }
  function removeDuty(id: string) { setDefinitions(current => current.length === 1 ? current : current.filter(duty => duty.id !== id)); setAssignments(current => current.filter(slot => slot.id !== id)); setScheduleMessage(null); }
  function clearAssignments() { setAssignments(current => current.map(duty => ({ ...duty, assignedStaffCode: "" }))); setScheduleMessage("Assignments cleared. Duty definitions have been kept for editing."); }
  function updateDuty(id: string, patch: Partial<DutyDefinitionRow>) { setDefinitions(current => current.map(duty => duty.id === id ? { ...duty, ...patch } : duty)); setScheduleMessage(null); }
  function updateAssignment(slotId: string, assignedStaffCode: string) { setAssignments(current => expandDutyDefinitions(definitions, current).map(slot => slot.slotId === slotId ? { ...slot, assignedStaffCode } : slot)); setScheduleMessage(null); }
  function runScheduler() { const result = autoScheduleDuties(expandDutyDefinitions(definitions, assignments), staff); setAssignments(result.duties); setScheduleMessage(result.summary.warnings.length ? "Auto-schedule completed with warnings. Review the summary before relying on it." : "Auto-schedule completed. Review the proposed assignments before relying on them."); }

  return <div className="mt-8 grid gap-8">
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-500">Active saved timetable</p><h2 className="mt-2 text-2xl font-bold text-slate-950">{timetable.name}</h2><p className="mt-2 text-sm text-slate-600">Source: <span className="font-semibold">{timetable.sourceFilename}</span> · Updated {new Date(timetable.updatedAt).toLocaleString()}</p></div><div className="grid gap-3 text-sm sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><p className="font-bold text-slate-500">Staff considered</p><p className="mt-1 text-2xl font-black text-slate-950">{staff.length}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="font-bold text-slate-500">P2 teachers by day</p><p className="mt-1 text-xs font-bold text-slate-950">{dayCountsText(p2Counts)}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="font-bold text-slate-500">P5 teachers by day</p><p className="mt-1 text-xs font-bold text-slate-950">{dayCountsText(p5Counts)}</p></div></div></div><p className="mt-4 rounded-2xl border border-sky-100 bg-sky-50 px-4 py-3 text-sm font-medium text-sky-900">This scheduler uses only the active saved timetable staff rows, including saved Tutor/Leadership edits and excluding staff removed before saving. Each duty definition below expands into Monday-Friday assignment slots, and Breaktime/Lunch preferences check P2/P5 on the same day as the slot.</p></section>

    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-500">Duty definition table</p><h2 className="mt-2 text-2xl font-bold text-slate-950">Define repeating duties</h2><p className="mt-2 text-sm text-slate-600">Add each duty once. The scheduler automatically creates Monday-Friday assignment slots.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={addDuty} className="rounded-full bg-amber-500 px-4 py-2 text-sm font-bold text-slate-950 hover:bg-amber-400">+ Add duty</button><button type="button" onClick={runScheduler} disabled={!staff.length || !definitions.length} className="rounded-full bg-slate-950 px-4 py-2 text-sm font-bold text-white hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-50">Auto-schedule duties</button><button type="button" onClick={clearAssignments} className="rounded-full border border-slate-300 px-4 py-2 text-sm font-bold text-slate-700 hover:bg-slate-50">Clear assignments</button></div></div>{scheduleMessage ? <p className="mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{scheduleMessage}</p> : null}<div className="mt-5 overflow-auto rounded-2xl border border-slate-200"><table className="min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-[0.14em] text-slate-500"><tr><th className="px-4 py-3">Description</th><th className="px-4 py-3">Time</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody>{definitions.map((duty, index) => <tr key={duty.id} className="border-t border-slate-100"><td className="px-4 py-3"><input value={duty.description} onChange={event => updateDuty(duty.id, { description: event.target.value })} placeholder={`Duty ${index + 1} location/description`} className="w-full rounded-2xl border border-slate-300 px-3 py-2" /></td><td className="px-4 py-3"><select value={duty.time} onChange={event => updateDuty(duty.id, { time: event.target.value as DutyTime })} className="w-full rounded-2xl border border-slate-300 px-3 py-2">{DUTY_TIME_OPTIONS.map(option => <option key={option} value={option}>{option}</option>)}</select></td><td className="px-4 py-3 text-right"><button type="button" onClick={() => removeDuty(duty.id)} disabled={definitions.length === 1} className="rounded-full border border-rose-200 px-3 py-1 text-xs font-bold text-rose-700 hover:bg-rose-50 disabled:cursor-not-allowed disabled:opacity-40">Remove</button></td></tr>)}</tbody></table></div></section>

    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-500">Generated assignment view</p><h2 className="mt-2 text-2xl font-bold text-slate-950">Monday-Friday duty slots</h2><div className="mt-5 overflow-auto rounded-2xl border border-slate-200"><table className="min-w-[1000px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-[0.14em] text-slate-500"><tr><th className="px-4 py-3">Day</th><th className="px-4 py-3">Time</th><th className="px-4 py-3">Description</th><th className="px-4 py-3">Assigned staff</th></tr></thead><tbody>{expandedAssignments.map(slot => <tr key={slot.slotId} className="border-t border-slate-100"><td className="px-4 py-3 font-semibold text-slate-900">{slot.day}</td><td className="px-4 py-3">{slot.time}</td><td className="px-4 py-3">{slot.description || "—"}</td><td className="px-4 py-3"><select value={slot.assignedStaffCode} onChange={event => updateAssignment(slot.slotId, event.target.value)} className="w-full rounded-2xl border border-slate-300 px-3 py-2"><option value="">Unassigned</option>{staff.map(member => <option key={member.staffCode} value={member.staffCode}>{staffDisplay(member)} · load {member.teachingLessonCount}{member.isLeadership ? " · leadership" : ""}{member.isTutor ? " · tutor" : ""}</option>)}</select></td></tr>)}</tbody></table></div></section>

    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-500">Review summary</p><h2 className="mt-2 text-2xl font-bold text-slate-950">Proposed schedule checks</h2><div className="mt-5 grid gap-4 md:grid-cols-5"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-500">Slots</p><p className="mt-1 text-3xl font-black">{summary.totalDuties}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-500">Staff</p><p className="mt-1 text-3xl font-black">{summary.staffConsidered}</p></div><div className="rounded-2xl bg-amber-50 p-4"><p className="text-xs font-bold uppercase text-amber-700">No break</p><p className="mt-1 text-3xl font-black">{summary.staffWithNoBreakDuty.length}</p></div><div className="rounded-2xl bg-amber-50 p-4"><p className="text-xs font-bold uppercase text-amber-700">No lunch</p><p className="mt-1 text-3xl font-black">{summary.staffWithNoLunchDuty.length}</p></div><div className="rounded-2xl bg-purple-50 p-4"><p className="text-xs font-bold uppercase text-purple-700">Leadership extra</p><p className="mt-1 text-3xl font-black">{summary.leadershipStaffWithExtraDuties.length}</p></div></div><div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 p-4"><h3 className="font-bold text-slate-950">Minimum expectation gaps</h3><p className="mt-2 text-sm text-slate-700"><span className="font-semibold">No Breaktime duty:</span> {names(summary.staffWithNoBreakDuty)}</p><p className="mt-2 text-sm text-slate-700"><span className="font-semibold">No Lunch duty:</span> {names(summary.staffWithNoLunchDuty)}</p><p className="mt-2 text-sm text-slate-700"><span className="font-semibold">Leadership with extra duties:</span> {names(summary.leadershipStaffWithExtraDuties)}</p></div><div className="rounded-2xl border border-slate-200 p-4"><h3 className="font-bold text-slate-950">Warnings / review notes</h3>{summary.warnings.length ? <ul className="mt-2 list-disc space-y-1 pl-5 text-sm font-medium text-amber-800">{summary.warnings.map(warning => <li key={warning}>{warning}</li>)}</ul> : <p className="mt-2 text-sm font-medium text-emerald-700">No warnings for the current proposed assignments.</p>}</div></div></section>
  </div>;
}
