export const TEMPLATE_VARIABLES: readonly ["studentName", "className", "assignmentTitle", "dueDate", "clarionLink"];
export const DEFAULT_EMAIL_TEMPLATES: { readonly homeworkSubject: string; readonly homeworkBody: string; readonly feedbackSubject: string; readonly feedbackBody: string };
export function validateTemplate(template: string, allowed?: readonly string[]): void;
export function renderTemplate(template: string, data: Record<string, string>): string;
export function renderSafeHtml(text: string, link: string, cta: string): string;
export function automaticEmailEnabled(env?: NodeJS.ProcessEnv): boolean;
export function getPublicMailDiagnostics(env?: NodeJS.ProcessEnv): { automaticEnabled: boolean; smtpConfigured: boolean; missing: string[]; senderName: string; senderAddress: string | null; baseUrlIsHttps: boolean };
export function getMailConfig(env?: NodeJS.ProcessEnv): { host: string; port: number; secure: boolean; requireTLS: boolean; auth: { user: string; pass: string }; from: { name: string; address: string } };
export function sanitiseMailError(error: unknown): string;
export function formatSchoolDueDate(date: Date, env?: NodeJS.ProcessEnv): string;
