import Link from "next/link";
import { EmailDeliveryStatus, UserRole } from "@prisma/client";
import { requireRole } from "../../../lib/auth";
import { getPublicMailDiagnostics } from "../../../lib/email-config";
import { getEmailSettings } from "../../../lib/email-notifications";
import { prisma } from "../../../lib/prisma";
import { resetEmailSettings } from "./actions";
import { EmailSettingsForm, RetryDeliveryForm, TestEmailForm } from "./email-settings-form";

export default async function EmailNotificationsAdminPage() {
  await requireRole(UserRole.ADMIN);
  const [settings, recent] = await Promise.all([getEmailSettings(), prisma.emailNotification.findMany({ orderBy: { createdAt: "desc" }, take: 25 })]);
  const diagnostics = getPublicMailDiagnostics();
  return <main className="mx-auto min-h-screen max-w-6xl px-6 py-12"><Link href="/" className="text-sm font-semibold text-amber-700">← Back to dashboard</Link><header className="mt-8 rounded-3xl bg-slate-950 p-8 text-white"><p className="text-xs font-bold uppercase tracking-widest text-amber-300">Clarion admin</p><h1 className="mt-3 text-4xl font-bold">Email Notifications</h1><p className="mt-3 text-slate-300">Configure safe student notification copy and inspect the database-backed delivery outbox. Mailbox secrets remain server-only.</p></header>
  <div className="mt-8 grid gap-8 lg:grid-cols-[1fr_1.4fr]"><div className="grid content-start gap-6"><section className="rounded-3xl border bg-white p-6"><h2 className="text-xl font-bold">Status & diagnostics</h2><dl className="mt-4 grid gap-2 text-sm"><div><dt className="font-semibold">Automatic delivery</dt><dd>{diagnostics.automaticEnabled ? "Enabled" : "Disabled (safe default)"}</dd></div><div><dt className="font-semibold">SMTP configuration</dt><dd>{diagnostics.smtpConfigured ? "Configured" : `Incomplete: ${diagnostics.missing.join(", ")}`}</dd></div><div><dt className="font-semibold">Sender</dt><dd>{diagnostics.senderName} {diagnostics.senderAddress ? `<${diagnostics.senderAddress}>` : "(address not configured)"}</dd></div><div><dt className="font-semibold">HTTPS application URL</dt><dd>{diagnostics.baseUrlIsHttps ? "Configured" : "Missing or not HTTPS"}</dd></div><div><dt className="font-semibold">School timezone</dt><dd>{diagnostics.schoolTimeZone}</dd></div></dl>{diagnostics.problems.length ? <div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-800"><p className="font-semibold">Automatic notifications will be recorded as skipped until these issues are fixed:</p><ul className="mt-1 list-disc pl-5">{diagnostics.problems.map((problem) => <li key={problem}>{problem}</li>)}</ul></div> : null}<TestEmailForm /></section><form action={resetEmailSettings}><button className="rounded-full border border-slate-300 bg-white px-5 py-2 text-sm font-bold">Reset both templates to safe defaults</button></form></div><EmailSettingsForm settings={settings} /></div>
  <section className="mt-8 rounded-3xl border bg-white p-6"><h2 className="text-xl font-bold">Recent delivery log</h2><div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Time</th><th className="p-3">Type</th><th className="p-3">Recipient</th><th className="p-3">Status</th><th className="p-3">Attempts / result</th></tr></thead><tbody>{recent.map((item) => <tr key={item.id} className="border-b align-top"><td className="p-3">{item.createdAt.toLocaleString()}</td><td className="p-3">{item.type}</td><td className="p-3">{item.recipientEmail}</td><td className="p-3">{item.status}</td><td className="p-3">{item.attemptCount}{item.lastError ? ` · ${item.lastError}` : ""}{item.status === EmailDeliveryStatus.FAILED ? <RetryDeliveryForm id={item.id} exhausted={item.attemptCount >= 5} /> : null}</td></tr>)}</tbody></table>{!recent.length ? <p className="py-6 text-slate-500">No notification records yet.</p> : null}</div></section></main>;
}
